### ISSUE TITLE
A problem of driving XM540-W270-R by using the youtube tutorial

### ISSUE THREAD

**Issue by AcarCopernicus** [ROBOTIS-GIT/DynamixelShield#24]
I am following all the instructions in the tutorial, but the servo is only blinking. is there anyone can drive the servo XM540 by using dynamixel2arduino library? 

the video link;
https://www.youtube.com/watch?v=M7x7oWyOdGw&t=57s&ab_channel=ROBOTISCustomerSupport

**Comment by ROBOTIS-Will** [comment]
This issue will be closed as there isn't recent activity. Please feel free to reopen when necessary.
